### ISSUE TITLE
Tổ chức allocate cho dự án 1 loại resrouce mới 2 lần nhưng ko tăng expected  quantity

### ISSUE THREAD

**Issue by AimKey** [kleqing/Dynamics#31]
1. Vào tổ chức
2. Send resource cho dự án (Cái resrouce mà dự án chưa có), VD: Táo - 1
3. Dự án accept -> Trong rs dự án sẽ là : Quantity 1, expected 1
4. Send lại resrouce cho dự án đó, VD: Táo - 1
5. Dự án accept -> Trong rs dự án là : Quantity 2, Expected 1

- Đề xuất: Tăng expected quantity hoặc làm gì đó chứ ko cô gõ cái đầu
![image](https://github.com/user-attachments/assets/0cb5defe-f0bc-4cfd-9425-d9f62960bfeb)

**Comment by tuantadev2664** [comment]
donate lần 1 thì auto đc.
nếu muốn donate lần 2 cùng với resource đó thì leadeer phải nâng hạn mức lên
