### ISSUE TITLE
homepage không view được success project

### ISSUE THREAD

**Issue by aurora-mei** [kleqing/Dynamics#41]
Guideline:
- đánh finish 1 project
- ra homepage, không thấy project vừa mới đánh finish

Discuss: đọc trong hàm Index của controller có thể là vì successfulProjectsPaginated lấy từ projectsQueryable, mà projectsQueryable lại chỉ lấy các project đang preparing hoặc in progress mà thôi
![Screenshot 2024-10-25 192700](https://github.com/user-attachments/assets/a5e4e560-7648-45e1-ae85-b29f70bc73d4)

**Comment by AimKey** [comment]
Ok đã fix
