### ISSUE TITLE
[Notification] User tạo tổ chức nhưng lại gửi thông báo là join ?

### ISSUE THREAD

**Issue by AimKey** [kleqing/Dynamics#42]
- Cái này có vẻ như là do bên @tuantadev2664 dùng hàm JoinOrg khi mà user tạo tổ chức ?

**Comment by desamma** [comment]
cái này do join với tạo tổ chức nằm ở cùng 1 chỗ

**Comment by AimKey** [comment]
Thế thì tìm cách xử lý chứ =)) Check role của ID gửi request join chẳng hạn
