### ISSUE TITLE
Trong lúc tạo project khi là CEO của tổ chức, nên thêm lựa chọn cho address

### ISSUE THREAD

**Issue by AimKey** [kleqing/Dynamics#43]
Cho CEO chọn 3 loại address thay vì chỉ 1 input
![image](https://github.com/user-attachments/assets/64bf9c3c-d6f3-4ca0-a9e4-e94c898b304a)

**Comment by tuantadev2664** [comment]
cái ni là sao thêm 1 lúc 3 địa chỉ hả hay sao? của project của request của org hả ?

**Comment by AimKey** [comment]
Ừa giống như bên address của tạo request với update user

**Comment by tuantadev2664** [comment]
xong
